sf/force-app/objects/Prompt__c/Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Prompt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf/force-app/main/default/objects/Prompt__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sf/force-app/main/default/objects/Prompt__c/fields/PromptHistory__c.field-meta.xml
<CustomField>
    <fullName>PromptHistory__c</fullName>
    <label>Prompt History</label>
    <referenceTo>PromptHistory__c</referenceTo>
    <relationshipLabel>Prompts</relationshipLabel>
    <relationshipName>Prompts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sf/force-app/objects/Prompt__c/fields/PromptResponse__c.field-meta.xml
<CustomField>
    <fullName>PromptResponse__c</fullName>
    <label>Prompt Response</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sf/force-app/objects/PromptHistory__c/PromptHistory__c.object-meta.xml
<CustomObject>
    <label>Prompt History</label>
    <nameField>
        <displayFormat>PH-{0000}</displayFormat>
        <label>PromptHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf/force-app/classes/QuestionAnswerUi.cls
public with sharing class QuestionAnswerUi {
    @AuraEnabled
    public static PromptResponse queryAnswer(String promptHistoryId, String question) {
        // We cannot do DML before callout so doing DML after.
        String answer = new LLMClient().callClient(question);

        if (promptHistoryId == null) {
            promptHistoryId = insertPromptHistoryAndReturnId();
        }

        createPromptRecord(promptHistoryId, question, answer);
        return new PromptResponse(promptHistoryId, answer);
    }

    private static Id insertPromptHistoryAndReturnId() {
        PromptHistory__c history = new PromptHistory__c();
        insert history;

        return history.Id;
    }

    private static void createPromptRecord(String promptHistoryId,
        String question, String answer) {
        // create Prompt record and link it to the promptHistory.
        Prompt__c promptRecord = new Prompt__c();
        promptRecord.Prompt__c = question;
        promptRecord.PromptResponse__c = answer;
        promptRecord.PromptHistory__c = promptHistoryId;

        insert promptRecord;
    }

    public class PromptResponse {
        @AuraEnabled
        public String promptHistoryId { get; set; }

        @AuraEnabled
        public String promptResponse { get; set; }

        public PromptResponse(String promptHistoryId, String promptResponse) {
            this.promptHistoryId = promptHistoryId;
            this.promptResponse = promptResponse;
        }
    }
}