sf/force-app/objects/Prompt__c/Prompt__c.object-meta.xml
<CustomObject>
    <label>Prompt</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Prompt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sf/force-app/main/default/objects/Prompt__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sf/force-app/main/default/objects/Prompt__c/fields/PromptHistory__c.field-meta.xml
<CustomField>
    <fullName>PromptHistory__c</fullName>
    <label>Prompt History</label>
    <referenceTo>PromptHistory__c</referenceTo>
    <relationshipLabel>Prompts</relationshipLabel>
    <relationshipName>Prompts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

sf/force-app/objects/Prompt__c/fields/PromptResponse__c.field-meta.xml
<CustomField>
    <fullName>PromptResponse__c</fullName>
    <label>Prompt Response</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sf/force-app/objects/PromptHistory__c/PromptHistory__c.object-meta.xml
<CustomObject>
    <label>Prompt History</label>
    <nameField>
        <displayFormat>PH-{0000}</displayFormat>
        <label>PromptHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Prompt History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sf/force-app/classes/PromptHistoryUi.cls
public with sharing class PromptHistoryUi {
    @AuraEnabled
    public static List<HistoryResponse> getPromptHistory() {
        List<PromptHistory__c> histories = [SELECT Id, (SELECT Id, Prompt__c, PromptResponse__c FROM Prompts__r) FROM
            PromptHistory__c];

        if (histories.isEmpty()) {
            return null;
        }

        List<HistoryResponse> responses = new List<PromptHistoryUi.HistoryResponse>();

        for (PromptHistory__c history : histories) {
            List<Prompt__c> prompts = history.Prompts__r;
            HistoryResponse response = new HistoryResponse(history.Id, prompts);

            responses.add(response);
        }

        return responses;
    }

    public class HistoryResponse {
        @AuraEnabled
        public String historyId { get; set; }

        @AuraEnabled
        public List<Prompt__c> prompts { get; set; }

        public HistoryResponse(String historyId, List<Prompt__c> prompts) {
            this.historyId = historyId;
            this.prompts = prompts;
        }

    }
}